"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, GripVertical, Plus, Save, Trash2 } from "lucide-react";
import { useFieldArray, useForm } from "react-hook-form";
import { WORKFLOW_CATEGORIES } from "@tasks-dash/contracts";
import { Button } from "@/components/atoms/button";
import { Card, CardContent, CardHeader } from "@/components/atoms/card";
import type { DemoStatus } from "@/features/demo/types";
import { workflowSchema, type WorkflowFormValues } from "../schemas/workflow-schema";
export function WorkflowBuilder({ statuses }: { statuses: DemoStatus[] }) { const form=useForm<WorkflowFormValues>({resolver:zodResolver(workflowSchema),defaultValues:{name:"Software delivery workflow",statuses}}); const fields=useFieldArray({control:form.control,name:"statuses"}); return <form onSubmit={form.handleSubmit(()=>undefined)} className="grid gap-6 xl:grid-cols-[1fr_360px]"><Card><CardHeader><div><h2 className="font-bold">Workflow statuses</h2><p className="text-sm text-slate-500">Reorder and customize the project lifecycle</p></div><Button type="button" size="sm" onClick={()=>fields.append({id:`status-${Date.now()}`,name:"New status",category:WORKFLOW_CATEGORIES.toDo,color:"#64748b",order:fields.fields.length})}><Plus size={14}/>Add status</Button></CardHeader><CardContent className="space-y-3">{fields.fields.map((field,index)=><div key={field.id} className="flex items-center gap-3 rounded-lg border p-3"><GripVertical size={17} className="text-slate-400"/><input {...form.register(`statuses.${index}.name`)} className="h-9 flex-1 rounded-md border px-3 text-sm"/><select {...form.register(`statuses.${index}.category`)} className="h-9 rounded-md border bg-white px-3 text-sm"><option value={WORKFLOW_CATEGORIES.toDo}>To do</option><option value={WORKFLOW_CATEGORIES.inProgress}>In progress</option><option value={WORKFLOW_CATEGORIES.done}>Done</option></select><input type="color" {...form.register(`statuses.${index}.color`)} className="size-9 rounded border p-1"/><Button type="button" variant="ghost" size="icon" onClick={()=>fields.remove(index)}><Trash2 size={15}/></Button></div>)}</CardContent></Card><div className="space-y-6"><Card><CardHeader><div><h2 className="font-bold">Transitions</h2><p className="text-sm text-slate-500">Allowed movements between statuses</p></div></CardHeader><CardContent className="space-y-3">{statuses.slice(0,-1).map((status,index)=><div className="flex items-center gap-2 text-sm" key={status.id}><span className="flex-1 rounded-md bg-slate-100 px-3 py-2">{status.name}</span><ArrowRight size={15}/><span className="flex-1 rounded-md bg-slate-100 px-3 py-2">{statuses[index+1].name}</span></div>)}</CardContent></Card><Button className="w-full" type="submit"><Save size={15}/>Save workflow</Button></div></form>; }
