import { Github, MessageCircle, Cloud, CheckCircle2, ExternalLink } from "lucide-react";
import { AppSidebar } from "@/components/organisms/app-sidebar";
import { TopHeader } from "@/components/organisms/top-header";
import { Card, CardContent } from "@/components/atoms/card";
import { Badge } from "@/components/atoms/badge";
import { Button } from "@/components/atoms/button";
import { demoData } from "@/features/demo/demo-data";
const integrations=[{name:"GitHub",description:"Link repositories, branches, commits, pull requests and webhooks.",icon:Github,state:"CONNECTED",detail:"khovan123 installation"},{name:"Discord",description:"Send workflow and delivery notifications to project channels.",icon:MessageCircle,state:"CONNECTED",detail:"#jira-issues"},{name:"Google Drive",description:"Browse each project's filtered folder tree and project documents.",icon:Cloud,state:"DEMO MODE",detail:"Configure OAuth credentials"}];
export default function IntegrationsPage(){return <><AppSidebar projects={demoData.projects}/><div className="ml-[260px] min-h-screen"><TopHeader title="Integrations" subtitle="Connect external delivery and documentation systems"/><main className="p-7"><div className="grid gap-5 xl:grid-cols-3">{integrations.map(({name,description,icon:Icon,state,detail})=><Card key={name}><CardContent className="pt-5"><div className="flex items-start justify-between"><div className="rounded-xl bg-slate-100 p-3"><Icon size={24}/></div><Badge className={state==="CONNECTED"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}>{state}</Badge></div><h2 className="mt-5 text-lg font-bold">{name}</h2><p className="mt-2 min-h-10 text-sm leading-5 text-slate-500">{description}</p><div className="mt-5 flex items-center gap-2 rounded-lg bg-slate-50 p-3 text-xs"><CheckCircle2 size={14} className="text-emerald-500"/><span className="flex-1">{detail}</span><ExternalLink size={13}/></div><Button className="mt-4 w-full" variant="secondary">Configure {name}</Button></CardContent></Card>)}</div></main></div></>}
